version: '3.8'

services:
  db:
    image: mariadb:11.7
    ports:
      - '3309:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: artisanal_db
      MARIADB_USER: artisanal_user
      MARIADB_PASSWORD: artisanal_password
    
  redis:
    image: redis:7.4-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'      
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  mariadb_data:
  redis_data: